# Avance 1. Análisis exploratorio de datos
---

In [1]:
import pandas as pd
import os

In [2]:
FILE_PATH = "../files/job_data"
FILE_NAME = "job_descriptions.csv"
job_data = pd.read_csv(os.path.join(FILE_PATH, FILE_NAME))

In [3]:
job_data.head()

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,...,001-381-930-7517x737,Digital Marketing Specialist,Social Media Manager,Snagajob,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie..."
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,...,461-509-4216,Web Developer,Frontend Web Developer,Idealist,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com..."
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525,...,9687619505,Operations Manager,Quality Control Manager,Jobs2Careers,Quality Control Managers establish and enforce...,"{'Legal Assistance, Bonuses and Incentive Prog...",Quality control processes and methodologies St...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P..."
3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,129896,...,+1-820-643-5431x47576,Network Engineer,Wireless Network Engineer,FlexJobs,"Wireless Network Engineers design, implement, ...","{'Transportation Benefits, Professional Develo...",Wireless network design and architecture Wi-Fi...,"Design, configure, and optimize wireless netwo...",Hess,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O..."
4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,53944,...,343.975.4702x9340,Event Manager,Conference Manager,Jobs2Careers,A Conference Manager coordinates and manages c...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Event planning Conference logistics Budget man...,Specialize in conference and convention planni...,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ..."

In [4]:
# TO DO: create experience and salary range info, mkn max and avg columns. also create a job posting date in date format

In [ ]:
def extract_string_range_data(df : pd.DataFrame, pattern : str, column : str, min_column : str, max_column : str):
    """
    """
    df[[min_column, max_column]] = (
    df[column]
    .str.extract(pattern)
    .astype(int)
)

In [5]:
job_data[["min_experience_years", "max_experience_years"]] = (
    job_data["Experience"]
    .str.extract(r"(\d+)\s*to\s*(\d+)")
    .astype(int)
)

In [6]:
job_data[["min_salary", "max_salary"]] = (
    job_data["Salary Range"]
    .str.extract(r"\$(\d+)K-\$(\d+)K")
    .astype(int)
)

job_data["min_salary"] = job_data["min_salary"] * 1000
job_data["max_salary"] = job_data["max_salary"] * 1000

In [7]:
job_data.head()

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Job Description,Benefits,skills,Responsibilities,Company,Company Profile,min_experience_years,max_experience_years,min_salary,max_salary
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,...,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie...",5,15,59000,99000
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,...,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com...",2,12,56000,116000
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525,...,Quality Control Managers establish and enforce...,"{'Legal Assistance, Bonuses and Incentive Prog...",Quality control processes and methodologies St...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P...",0,12,61000,104000
3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,129896,...,"Wireless Network Engineers design, implement, ...","{'Transportation Benefits, Professional Develo...",Wireless network design and architecture Wi-Fi...,"Design, configure, and optimize wireless netwo...",Hess,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O...",4,11,65000,91000
4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,53944,...,A Conference Manager coordinates and manages c...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Event planning Conference logistics Budget man...,Specialize in conference and convention planni...,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ...",1,12,64000,87000

¿Hay valores faltantes en el conjunto de datos? ¿Se pueden identificar patrones de ausencia? 

No se encuentran datos vacío, la razón es porque es un dataset autogenerado.

In [8]:
job_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1615940 entries, 0 to 1615939
Data columns (total 27 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Job Id                1615940 non-null  int64
 1   Experience            1615940 non-null  object
 2   Qualifications        1615940 non-null  object
 3   Salary Range          1615940 non-null  object
 4   location              1615940 non-null  object
 5   Country               1615940 non-null  object
 6   latitude              1615940 non-null  float64
 7   longitude             1615940 non-null  float64
 8   Work Type             1615940 non-null  object
 9   Company Size          1615940 non-null  int64
 10  Job Posting Date      1615940 non-null  object
 11  Preference            1615940 non-null  object
 12  Contact Person        1615940 non-null  object
 13  Contact               1615940 non-null  object
 14  Job Title             1615940 non-null  object
 15  Role                  1615940 non-null  object
 16  Job Portal            1615940 non-null  object
 17  Job Description       1615940 non-null  object
 18  Benefits              1615940 non-null  object
 19  skills                1615940 non-null  object
 20  Responsibilities      1615940 non-null  object
 21  Company               1615940 non-null  object
 22  Company Profile       1610462 non-null  object
 23  min_experience_years  1615940 non-null  int64
 24  max_experience_years  1615940 non-null  int64
 25  min_salary            1615940 non-null  int64
 26  max_salary            1615940 non-null  int64
dtypes: float64(2), int64(6), object(19)
memory usage: 332.9+ MB

¿Cuáles son las estadísticas resumidas del conjunto de datos?

In [9]:
job_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Job Id,1615940.0,1.548935e+15,8.946722e+14,1.817948e+11,7.740508e+14,1.547858e+15,2.323729e+15,3.099618e+15
latitude,1615940.0,1.937743e+01,2.355690e+01,-4.090060e+01,5.152100e+00,1.807080e+01,3.907420e+01,7.170690e+01
longitude,1615940.0,1.639926e+01,7.066762e+01,-1.751982e+02,-1.531010e+01,1.914510e+01,4.757690e+01,1.780650e+02
Company Size,1615940.0,7.370467e+04,3.529886e+04,1.264600e+04,4.311400e+04,7.363300e+04,1.043000e+05,1.348340e+05
min_experience_years,1615940.0,2.501808e+00,1.707809e+00,0.000000e+00,1.000000e+00,3.000000e+00,4.000000e+00,5.000000e+00
max_experience_years,1615940.0,1.149798e+01,2.291933e+00,8.000000e+00,9.000000e+00,1.100000e+01,1.300000e+01,1.500000e+01
min_salary,1615940.0,6.000343e+04,3.163964e+03,5.500000e+04,5.700000e+04,6.000000e+04,6.300000e+04,6.500000e+04
max_salary,1615940.0,1.049789e+05,1.471749e+04,8.000000e+04,9.200000e+04,1.050000e+05,1.180000e+05,1.300000e+05

In [10]:
job_data.describe(exclude='number').T

,count,unique,top,freq
Experience,1615940,48,5 to 8 Years,34120
Qualifications,1615940,10,BBA,162148
Salary Range,1615940,561,$59K-$88K,3043
location,1615940,214,Seoul,15104
Country,1615940,216,Malta,7723
Work Type,1615940,5,Part-Time,324044
Job Posting Date,1615940,731,2021-11-14,2378
Preference,1615940,3,Male,539167
Contact Person,1615940,367128,Michael Smith,838
Contact,1615940,1615933,518.951.8103,2
Job Title,1615940,147,UX/UI Designer,48551
Role,1615940,376,Interaction Designer,20580
Job Portal,1615940,16,FlexJobs,129879
Job Description,1615940,376,Interaction Designers specialize in designing ...,20580
Benefits,1615940,11,"{'Childcare Assistance, Paid Time Off (PTO), R...",161924
skills,1615940,376,Interaction design principles User behavior an...,20580
Responsibilities,1615940,375,"Work on interaction design, defining how users...",20580
Company,1615940,888,DTE Energy,1957
Company Profile,1610462,884,"{""Sector"":""Automotive"",""Industry"":""Automotive""...",3572

¿Hay valores atípicos en el conjunto de datos?

¿Cuál es la cardinalidad de las variables categóricas?

¿Existen distribuciones sesgadas en el conjunto de datos? ¿Necesitamos aplicar alguna transformación no lineal?

¿Se identifican tendencias temporales? (En caso de que el conjunto incluya una dimensión de tiempo).

¿Hay correlación entre las variables dependientes e independientes?

¿Cómo se distribuyen los datos en función de diferentes categorías? (análisis bivariado)

¿Hay desequilibrio en las clases de la variable objetivo?

# Extraccion de datos de pdf
---

In [1]:
import pymupdf4llm
import os
from pypdf import PdfReader
from unstructured.partition.auto import partition

In [2]:
FILE_PATH = "../files/input_cv"
FILE_NAME = "cv_test.pdf"

## pymupdf4llm — The Markdown Generator

In [3]:
markdown = pymupdf4llm.to_markdown(os.path.join(FILE_PATH, FILE_NAME))
print(markdown)

## **ALONSO PEDRERO MARTINEZ[´]**

� /AloPedrero � /alonso-pedrero-martinez �pedreromartinezalonso@gmail.com � Toluca, Edo. de M´exico, M´exico � (+52) 722-431-4626

## **EDUCATION**

**Tecnol´ogico de Monterrey (ITESM), M´exico** _Jan 2019 - Jun 2023 B.S. in Mechatronic Engineering GPA: 91_ **Tecnol´ogico de Monterrey (ITESM), M´exico** _Sep 2023 - Currently studying M.S. in Applied Artificial Intelligence Current GPA: 94_

## **SKILLS**

**Programming Languages: Frameworks & Libraries: Tools & Platforms:**

Python, TypeScript, Java, SQL React, Next.js, Spring Boot, Pandas, Scikit-learn, NumPy, PySpark, Tailwind CSS Docker, GitHub, Linux/Unix (Bash, Zsh), AWS, Azure, Google Cloud, Clerk

_Spoken languages: Spanish (native), English (advanced)_

## **WORK EXPERIENCE**

## **Data Analyst**

**PepsiCo** _M´exico City, M´exico_ — **01/2024 - 02/2026**

- Led the semi-automation of a **$50K** report using **Alteryx** , consolidating data from **various sources** and **reducing processing time by 600%** . Enabled users to generate reports by simply downloading data and adjusting two variables. - **Developed the first machine learning project** in Supply Chain at PepsiCo Beverages North America, identifying a **$31M** opportunity in **waste prediction** and a **$40M** opportunity in **product coaching recommendations** . Built scalable **Random Forest regression and classification models** , as well as SVD-based **recommendation systems** , with a training and production pipeline capable of handling weekly data ingests across North America.

- Established **documentation and development standards** for change requests, error mitigation, and project tracking. Defined Python **best practices** based on **PEP8, Clean Code, and OOP** , ensuring **scalability, testability, and code reusability** .

**Data Scientist, Intern Daimler** _M´exico City, M´exico_ — **04/2023 - 01/2024** - Developed an automated software architecture using **Docker** to streamline the extraction, transformation, and accessibility of **Salesforce** data, reducing data operation time by **90%** . Ensured compliance with migration guidelines while enhancing data workflows.

- Performed in-depth analyzes using **Excel, Power BI, Microsoft SQL Server and Python** to identify critical failures and optimize client satisfaction. Deliver actionable business recommendations through reports and visualizations, fostering cross-department collaboration.

## **PROJECTS**

## **Calendra App – Full-Stack Scheduling Platform**

- **Built a scheduling web app** using React, Next.js 15 and TypeScript with event types and user availability management.

- **Implemented authentication and scheduling logic** with Clerk and server actions, storing data in SQL and deploying on Vercel.

## **Cloud File Storage API – Full-Stack File Upload System**

- **Built a file upload system** using React and Spring Boot 3 with a REST API for file management.

- **Integrated AWS S3 for storage** and containerized the backend with Docker while persisting metadata in SQL.

## **AWARDS**

- Hackathon: First place - ”Fun Wellness”. (ITESM Toluca Campus, 2022)

- Hackathon: First place - ”Virtual Hack N’ Jam”. (ITESM Toluca Campus, 2020)

- Hackathon: First place - ”The world against pollution” (ITESM Toluca Campus, 2019)

- Hackathon: Second place - ”Fintech” (ITESM Toluca Campus, 2019)

What I got: Clean markdown output in 0.14 seconds with proper headings and table formatting. Surprisingly good results. Makes errors that can be cleaned due to the accents. The results are created in markdown.


Good for: Content systems, documentation processing, when you need structured text that preserves hierarchy.


Consider if: You’re dealing with complex multi-column layouts that might get scrambled.

## pypdf — The Reliable Default

In [4]:
reader = PdfReader(os.path.join(FILE_PATH, FILE_NAME))
text = "\n".join(p.extract_text() for p in reader.pages)
print(text)

ALONSO PEDRERO MART´INEZ
/gtb/AloPedrero /♀nedn/alonso-pedrero-martinez pedreromartinezalonso@gmail.com
 Toluca, Edo. de M´exico, M´exico /ne(+52) 722-431-4626
EDUCATION
Tecnol´ogico de Monterrey (ITESM), M´exico Jan 2019 - Jun 2023
B.S. in Mechatronic Engineering GPA: 91
Tecnol´ogico de Monterrey (ITESM), M´exico Sep 2023 - Currently studying
M.S. in Applied Artificial Intelligence Current GPA: 94
SKILLS
Programming Languages: Python, TypeScript, Java, SQL
Frameworks & Libraries: React, Next.js, Spring Boot, Pandas, Scikit-learn, NumPy, PySpark, Tailwind CSS
Tools & Platforms: Docker, GitHub, Linux/Unix (Bash, Zsh), AWS, Azure, Google Cloud, Clerk
Spoken languages: Spanish (native), English (advanced)
WORK EXPERIENCE
Data Analyst PepsiCo M´exico City, M´exico — 01/2024 - 02/2026
- Led the semi-automation of a $50K report using Alteryx, consolidating data from various sources and reducing
processing time by 600%. Enabled users to generate reports by simply downloading data and adjusting two variables.
- Developed the first machine learning project in Supply Chain at PepsiCo Beverages North America, identifying
a $31M opportunity in waste prediction and a $40M opportunity in product coaching recommendations . Built
scalable Random Forest regression and classification models , as well as SVD-based recommendation systems,
with a training and production pipeline capable of handling weekly data ingests across North America.
- Established documentation and development standardsfor change requests, error mitigation, and project tracking.
Defined Python best practices based on PEP8, Clean Code, and OOP , ensuring scalability, testability, and code
reusability.
Data Scientist, Intern Daimler M´exico City, M´exico — 04/2023 - 01/2024
- Developed an automated software architecture using Docker to streamline the extraction, transformation, and acces-
sibility of Salesforce data, reducing data operation time by90%. Ensured compliance with migration guidelines while
enhancing data workflows.
- Performed in-depth analyzes using Excel, Power BI, Microsoft SQL Server and Python to identify critical fail-
ures and optimize client satisfaction. Deliver actionable business recommendations through reports and visualizations,
fostering cross-department collaboration.
PROJECTS
Calendra App – Full-Stack Scheduling Platform
- Built a scheduling web app using React, Next.js 15 and TypeScript with event types and user availability manage-
ment.
- Implemented authentication and scheduling logicwith Clerk and server actions, storing data in SQL and deploying
on Vercel.
Cloud File Storage API – Full-Stack File Upload System
- Built a file upload system using React and Spring Boot 3 with a REST API for file management.
- Integrated A WS S3 for storageand containerized the backend with Docker while persisting metadata in SQL.
A W ARDS
- Hackathon: First place - ”Fun Wellness”. (ITESM Toluca Campus, 2022)
- Hackathon: First place - ”Virtual Hack N’ Jam”. (ITESM Toluca Campus, 2020)
- Hackathon: First place - ”The world against pollution” (ITESM Toluca Campus, 2019)
- Hackathon: Second place - ”Fintech” (ITESM Toluca Campus, 2019)

What I got: Solid text extraction with occasional spacing quirks. Works everywhere, no C dependencies. Makes mistakes with accents, clear text and good structure


Good for: Lambda functions, containerised apps, environments where you can’t compile extensions.


Consider if: Text fidelity is critical for your downstream processing

## unstructured — The Semantic Chunker

In [5]:
blocks = partition(filename = os.path.join(FILE_PATH, FILE_NAME))
for block in blocks:
    print(f"{block.category}: {block.text}")

/Users/alonsopedreromartinez/Documents/GitHub/tareas-nlp-mna21-aj-2026-AloPedrero/activities/activity 1/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
No languages specified, defaulting to English.

Header: ALONSO PEDRERO MART´INEZ
NarrativeText: (cid:135) /AloPedrero ﬂ /alonso-pedrero-martinez pedreromartinezalonso@gmail.com Toluca, Edo. de M´exico, M´exico (cid:211) (+52) 722-431-4626
Title: EDUCATION
Title: Tecnol´ogico de Monterrey (ITESM), M´exico B.S. in Mechatronic Engineering
UncategorizedText: Jan 2019 - Jun 2023 GPA: 91
Title: Tecnol´ogico de Monterrey (ITESM), M´exico M.S. in Applied Artificial Intelligence
Title: Sep 2023 - Currently studying Current GPA: 94
Title: SKILLS
Title: Programming Languages: Frameworks & Libraries: Tools & Platforms:
UncategorizedText: Python, TypeScript, Java, SQL React, Next.js, Spring Boot, Pandas, Scikit-learn, NumPy, PySpark, Tailwind CSS Docker, GitHub, Linux/Unix (Bash, Zsh), AWS, Azure, Google Cloud, Clerk
NarrativeText: Spoken languages: Spanish (native), English (advanced)
Title: WORK EXPERIENCE
NarrativeText: Data Analyst M´exico City, M´exico — 01/2024 - 02/2026 - Led the semi-automation of a $50K report using Alteryx, consolidating data from various sources and reducing processing time by 600%. Enabled users to generate reports by simply downloading data and adjusting two variables. - Developed the first machine learning project in Supply Chain at PepsiCo Beverages North America, identifying a $31M opportunity in waste prediction and a $40M opportunity in product coaching recommendations. Built scalable Random Forest regression and classification models, as well as SVD-based recommendation systems, with a training and production pipeline capable of handling weekly data ingests across North America. - Established documentation and development standards for change requests, error mitigation, and project tracking. Defined Python best practices based on PEP8, Clean Code, and OOP, ensuring scalability, testability, and code reusability. Data Scientist, Intern M´exico City, M´exico — 04/2023 - 01/2024 - Developed an automated software architecture using Docker to streamline the extraction, transformation, and acces- sibility of Salesforce data, reducing data operation time by 90%. Ensured compliance with migration guidelines while enhancing data workflows. - Performed in-depth analyzes using Excel, Power BI, Microsoft SQL Server and Python to identify critical fail- ures and optimize client satisfaction. Deliver actionable business recommendations through reports and visualizations, fostering cross-department collaboration.
NarrativeText: PepsiCo
Title: Daimler
Title: PROJECTS
NarrativeText: Calendra App – Full-Stack Scheduling Platform - Built a scheduling web app using React, Next.js 15 and TypeScript with event types and user availability manage- ment. - Implemented authentication and scheduling logic with Clerk and server actions, storing data in SQL and deploying on Vercel.
NarrativeText: Cloud File Storage API – Full-Stack File Upload System - Built a file upload system using React and Spring Boot 3 with a REST API for file management. - Integrated AWS S3 for storage and containerized the backend with Docker while persisting metadata in SQL.
Title: AWARDS
Footer: - Hackathon: First place - ”Fun Wellness”. (ITESM Toluca Campus, 2022) - Hackathon: First place - ”Virtual Hack N’ Jam”. (ITESM Toluca Campus, 2020) - Hackathon: First place - ”The world against pollution” (ITESM Toluca Campus, 2019) - Hackathon: Second place - ”Fintech” (ITESM Toluca Campus, 2019)

What I got: Semantically labelled chunks (Title, NarrativeText, etc.) in 1.11 seconds. Perfect for downstream processing. Separates everything with Title, Headers, NarrativeText and Footers with the ability to specify the language.


Good for: RAG systems, document analysis, when you need meaningful content boundaries for embedding

# Referencias
---
Kumar, A. K. (2025, July 21). I Tested 7 Python PDF Extractors So You Don’t Have To (2025 Edition). Medium. Retrieved May 5, 2026, from https://onlyoneaman.medium.com/i-tested-7-python-pdf-extractors-so-you-dont-have-to-2025-edition-c88013922257